[package]
name = "pio" # the name of the package
version = "0.1.0"    # the current version, obeying semver
authors = ["clueless_@live.co.uk"]

[lib]
crate-type = ["rlib"]
name = "pio"
path = "src/lib.rs"

[dependencies]
rlibc = "1.0.0"

